{
 "title": "Floatplane Downloader",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Queued",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(queued)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Downloaded",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(increase(downloaded_total[5y]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes Downloaded",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(increase(downloaded_bytes_total[5y]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(downloaded_bytes_total[$__rate_interval])) * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(instance)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Instances",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "count by(version) (avg_over_time(instance[1m]))",
     "legendFormat": "v{{version}}"
    }
   ]
  },
  {
   "title": "Download Speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(downloaded_bytes_total[$__rate_interval])) * 8",
     "legendFormat": "Speed"
    }
   ]
  },
  {
   "title": "Endpoint Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(avg by(pathname, status) (increase(request_duration_ms_sum{hostname!=\"pbs.floatplane.com\"}[$__rate_interval]))) / avg by(pathname, status) (increase(request_duration_ms_count{hostname!=\"pbs.floatplane.com\"}[$__rate_interval])) > 0",
     "legendFormat": "{{pathname}} ({{status}})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_user_seconds_total{job=\"fpd\"}[$__rate_interval])",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "Endpoint Requests",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum by(pathname, status) (rate(request_duration_ms_count{hostname!=\"pbs.floatplane.com\"}[$__rate_interval]) * 60) > 0",
     "legendFormat": "{{pathname}} ({{status}})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(process_resident_memory_bytes{job=\"fpd\"}[1m]))",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(message) (increase(errors[$__rate_interval])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instance Scrape Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=\"fpd\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}