name: "[dev] Validate & Build"

on:
 push:
  branches:
   - "dev"
 pull_request:
  types: ["opened", "edited", "reopened", "synchronize", "ready_for_review", "review_requested"]

jobs:
 # eslint Check
 eslint:
  name: eslint
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v4

   - uses: reviewdog/action-eslint@v1
     with:
      reporter: github-check
      eslint_flags: src/
      github_token: ${{ secrets.GITHUB_TOKEN }}

 # Binary Build & Test (depends on eslint)
 Sanity:
  name: Build & Sanity Check
  needs: eslint
  strategy:
   matrix:
    runs-on: [ubuntu-latest, windows-latest]
  runs-on: ${{ matrix.runs-on }}

  steps:
   - uses: actions/checkout@v4

   - name: Install pnpm 📥
     uses: pnpm/action-setup@v4
     with:
      version: latest

   - name: Install Node.js 📥
     uses: actions/setup-node@v4
     with:
      cache: pnpm
      node-version: latest

   - name: Install dependencies 📥
     run: pnpm install

   - name: Test ESM
     run: pnpm run test-esm

   - name: Build Binaries
     run: pnpm run build-${{ matrix.runs-on }}

   - name: Test Build Binaries
     run: pnpm run test-${{ matrix.runs-on }}

   - name: Upload Build Artifact
     uses: actions/upload-artifact@v4
     with:
      name: build-${{ matrix.runs-on }}
      path: ./build/

 # Release to GitHub (runs after tests)
 Release:
  name: Release dev build on GitHub
  needs: Sanity
  runs-on: ubuntu-latest

  steps:
   - name: Download All Artifacts
     uses: actions/download-artifact@v4
     with:
      path: ./build/
      merge-multiple: true

   - name: Publish dev release on GitHub
     uses: marvinpinto/action-automatic-releases@latest
     with:
      repo_token: ${{ secrets.GITHUB_TOKEN }}
      automatic_release_tag: dev
      prerelease: true
      title: Latest
      files: build/*

 # Release to DockerHub (runs after tests)
 DockerHub:
  name: Publish dev build to DockerHub
  needs: Sanity
  runs-on: ubuntu-latest

  steps:
   - name: Set up Docker Buildx
     uses: docker/setup-buildx-action@v3

   - name: Login to DockerHub
     uses: docker/login-action@v3
     with:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}

   - name: Build & Publish dev on DockerHub
     uses: docker/build-push-action@v5
     with:
      push: true
      tags: inrix/floatplane-downloader:dev
      cache-from: type=gha
      cache-to: type=gha,mode=max
