name: "[master] PullRequest ensure dev"

on:
 pull_request_target:
  types: [opened, edited]

jobs:
 check-branch:
  runs-on: ubuntu-latest
  permissions:
   pull-requests: write
  steps:
   - uses: Vankka/pr-target-branch-action@v3
     env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     with:
      target: master
      exclude: dev # Don't prevent going from development -> main
      change-to: dev
      comment: |
       Your PR's base branch was set to `master`, PRs should be set to target the `dev` branch.
       The base branch of this PR has been automatically changed to `dev`, please check that there are no merge conflicts
