name: "[master] Release"

on:
 push:
  branches:
   - "master"
  paths-ignore:
   - "**/*.md"
   - ".vscode/**"
   - "artwork/**"
   - "wiki/**"

jobs:
 Build:
  uses: ./.github/workflows/build.yml

 Release:
  name: Draft latest release on GitHub
  needs: Build
  runs-on: ubuntu-latest

  steps:
   - name: Download All Artifacts
     uses: actions/download-artifact@v4
     with:
      path: ./build/
      merge-multiple: true

   - name: Publish latest draft release on GitHub
     uses: marvinpinto/action-automatic-releases@latest
     with:
      repo_token: ${{ secrets.GITHUB_TOKEN }}
      automatic_release_tag: latest
      draft: true
      title: Latest Release
      files: build/*

 DockerHub:
  name: Publish latest build to DockerHub
  needs: Build
  runs-on: ubuntu-latest

  steps:
   - name: Set up QEMU
     uses: docker/setup-qemu-action@v3

   - name: Set up Docker Buildx
     uses: docker/setup-buildx-action@v3

   - name: Login to DockerHub
     uses: docker/login-action@v3
     with:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}

   - name: Build & Publish latest on DockerHub
     uses: docker/build-push-action@v5
     with:
      push: true
      tags: inrix/floatplane-downloader:latest
      cache-from: type=gha
      cache-to: type=gha,mode=max
      platforms: linux/amd64,linux/arm64
